
name: Build and Push with Kaniko

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Docker Image with Kaniko
        uses: imranismail/setup-kaniko@v2
        with:
          dockerfile: Dockerfile
          context: .
          image: cr.selcloud.ru/hootregistry/test-front:v0.0.1 
          credentials: |
            {
              docker_login: ${{ secrets.DOCKER_USERNAME }},
              docker_token: ${{ secrets.DOCKER_TOKEN }}
            }

